ci(lefthook): posix compliant check tools job
Signed-off-by: Amir Zarrinkafsh <nightah@me.com>

diff --git a/.lefthook.yml b/.lefthook.yml
--- a/.lefthook.yml
+++ b/.lefthook.yml
@@ -5,25 +5,24 @@ pre-commit:
     - name: check tools
       # yamllint disable rule:indentation
       run: |
-        MISSING=()
+        MISSING=""
+        COUNT=0
 
         for TOOL in gitleaks golangci-lint pnpm yamllint; do
-          if ! command -v ${TOOL} > /dev/null 2>&1; then
-          MISSING+=("${TOOL}")
+          if ! command -v ${TOOL} >/dev/null 2>&1; then
+            if [ "$COUNT" -eq 0 ]; then
+              MISSING=${TOOL}
+            elif [ "$COUNT" -eq 1 ]; then
+              MISSING="${MISSING} and ${TOOL}"
+            else
+              MISSING="$(echo "${MISSING}" | sed 's/ and /, /') and ${TOOL}"
+            fi
+            COUNT=$((COUNT + 1))
           fi
         done
 
-        if [ ${#MISSING[@]} -gt 0 ]; then
-          COUNT=${#MISSING[@]}
-          if [ $COUNT -eq 1 ]; then
-            LIST="${MISSING[0]}"
-          elif [ $COUNT -eq 2 ]; then
-            LIST="${MISSING[0]} and ${MISSING[1]}"
-          else
-            LIST="$(IFS=, ; echo "${MISSING[*]:0:$COUNT-1}" | sed 's/,/, /g') and ${MISSING[$COUNT-1]}"
-          fi
-
-          echo "❌ You must install ${LIST}"
+        if [ ${COUNT} -gt 0 ]; then
+          echo "❌ You must install ${MISSING}"
           exit 1
         fi
       # yamllint enable rule:indentation
